/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bdgenomics.formats.avro;  
@SuppressWarnings("all")
/** Enumeration of the possible genders. */
@org.apache.avro.specific.AvroGenerated
public enum Gender { 
  Male, Female, Unknown  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"org.bdgenomics.formats.avro\",\"doc\":\"Enumeration of the possible genders.\",\"symbols\":[\"Male\",\"Female\",\"Unknown\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
