/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bdgenomics.formats.avro;  
@SuppressWarnings("all")
/** An enumeration that describes the allele that corresponds to a genotype. Can take
 the following values:

 * Ref: The genotype is the reference allele
 * Alt: The genotype is the alternate allele
 * OtherAlt: The genotype is an unspecified other alternate allele. This occurs
   in our schema when we have split a multi-allelic genotype into two genotype
   records.
 * NoCall: The genotype could not be called. */
@org.apache.avro.specific.AvroGenerated
public enum GenotypeAllele { 
  Ref, Alt, OtherAlt, NoCall  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GenotypeAllele\",\"namespace\":\"org.bdgenomics.formats.avro\",\"doc\":\"An enumeration that describes the allele that corresponds to a genotype. Can take\\n the following values:\\n\\n * Ref: The genotype is the reference allele\\n * Alt: The genotype is the alternate allele\\n * OtherAlt: The genotype is an unspecified other alternate allele. This occurs\\n   in our schema when we have split a multi-allelic genotype into two genotype\\n   records.\\n * NoCall: The genotype could not be called.\",\"symbols\":[\"Ref\",\"Alt\",\"OtherAlt\",\"NoCall\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
