/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bdgenomics.formats.avro;  
@SuppressWarnings("all")
/** An enumeration that describes the characteristics of a genotype at a site. Can
 take the following values:

 * HOM_REF: All genotypes at this site were called as the reference allele.
 * HET: Genotypes at this site were called as multiple different alleles. This
   most commonly occurs if a diploid sample's genotype contains one reference
   and one variant allele, but can also occur if the genotype contains multiple
   alternate alleles.
 * HOM_ALT: All genotypes at this site were called as a single alternate allele.
 * NO_CALL: The genotype could not be called at this site. */
@org.apache.avro.specific.AvroGenerated
public enum GenotypeType { 
  HOM_REF, HET, HOM_ALT, NO_CALL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GenotypeType\",\"namespace\":\"org.bdgenomics.formats.avro\",\"doc\":\"An enumeration that describes the characteristics of a genotype at a site. Can\\n take the following values:\\n\\n * HOM_REF: All genotypes at this site were called as the reference allele.\\n * HET: Genotypes at this site were called as multiple different alleles. This\\n   most commonly occurs if a diploid sample's genotype contains one reference\\n   and one variant allele, but can also occur if the genotype contains multiple\\n   alternate alleles.\\n * HOM_ALT: All genotypes at this site were called as a single alternate allele.\\n * NO_CALL: The genotype could not be called at this site.\",\"symbols\":[\"HOM_REF\",\"HET\",\"HOM_ALT\",\"NO_CALL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
