/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bdgenomics.formats.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Strand { 
  Forward, Reverse, Independent  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Strand\",\"namespace\":\"org.bdgenomics.formats.avro\",\"symbols\":[\"Forward\",\"Reverse\",\"Independent\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
